### PR TITLE
Project infrastructure

### PR DESCRIPTION
**Pull request by yasha1212**

### CODE REVIEW

**Review by ilyahumbar — CHANGES_REQUESTED** [review]
Reommended reading related to project staructure in general and repository/UoW patterns in partucular:
https://garywoodfine.com/generic-repository-pattern-net-core/ (it would also be great to follow the links to other posts in that article for better understanding)

Suggested project struecture (and what is expected to be in each project):

 - [x] Update structure to be the following
  - ItechArt.Common (utils, extensions)
  - ItechArt.SurveyCreator.WebApp (ASP.NET Core MVC, DI, configuration, startup, controllers, views)
  - ItechArt.SurveyCreator.Foundation (business logic - services)
  - ItechArt.SurveyCreator.DAL (Entities, DbContext, migrations etc)

 - [x] Use .Net 5 target
 - [x] Remove `Password` field from `User` entity
 - [x] Use empty lines between properties and interface members
 - [x] Strongly typed methods in service. If you want an additional layer of astraction around EF core context, then use Repository pattern as described in the article above
 
 Couple of questions:
 1. Are exceptions logged?
 2. Are you ready to use EF Core migrations?
 3. Have you tested your service works as expected?

**Comment by yasha1212** [comment]
1. There are some test exceptions, that are throwed by UserService, and they are handled and logged by controller.
2. Yes, I am ready to use migrations, and I've already created the first initial migration for my database model.
3. I've tested my service with the help of some pages and controller. As the result I can affirm that it works as expected.

**Comment by yasha1212** [comment]
Now every exception in application is logged and rethrowed to be handled by specific middleware.

**Comment by ilyahumbar** [comment]
- [x]  Pay attention to naming The following entities need to be renamed: `DatabaseContext `, `IEntityService`, `DatabaseController `.
- [x]  You also should consider reducing nesting of logic by inverting conditions, especially in case of validation 
e.g. Instead of this
```c#
if (someEntity != null)
{
   // some processing logic here which is longer than one line
   return SomeSuccessResult;
}
// when you are reading this line you should mentally preserve the context `someEntity == null` here
return SomeErrorResult
```
consider 
```c#
if (someEntity == null)
{
   return SomeErrorResult
}
// some processing logic here 
return SomeSuccessResult;
```

- [x]   Put middleware extensions close to middleware itself

**Pull request merged**
